- job:
    name: ceph-pr-clang-tidy
    node: small
    project-type: freestyle
    defaults: global
    display-name: 'ceph: Clang-tidy checks'
    concurrent: true
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 15
          artifact-days-to-keep: 15
      - github:
          url: https://github.com/ceph/ceph/

  scm:
  - git:
      url: https://github.com/ceph/ceph.git
      name: origin
      branches:
        - origin/pr/${ghprbPullId}/merge
      refspec: +refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*
      skip-tag: true
      shallow-clone: true
      honor-refspec: true
      timeout: 20

  triggers:
  - github-pull-request:
      allow-whitelist-orgs-as-admins: true
      org-list:
        - ceph
      trigger-phrase: 'jenkins test clang-tidy'
      only-trigger-phrase: false
      github-hooks: true
      permit-all: true
      auto-close-on-fail: false
      status-context: "Clang-tidy lint check"
      started-status: "checking if bugs exist"
      success-status: "no bugs found"
      failure-status: "bugs found"

  builders:
  - shell:
      !include-raw:
        - ../../../scripts/build_utils.sh
        - ../../build/build
        - ../../build/clang-tidy-to-junit.py

  publishers:
  - junit:
      results: report.xml
      allow-empty-results: true
